# Generated by Django 3.0.7 on 2020-11-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
            preserve_default=False,
        ),
    ]
