# Generated by Django 3.0.7 on 2020-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
