# Generated by Django 3.0.7 on 2020-09-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0004_auto_20200907_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
