# Generated by Django 3.0.7 on 2020-09-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0005_auto_20200907_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(),
        ),
    ]
